project:
  type: website
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Presentations"
        contents:
          - exploratory_data_analysis.qmd
         
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

