project:
  type: website
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Teaching"
        contents:
          - text: "Exploratory data analysis"
            href: exploratory_data_analysis.qmd
      - section: "Presentations"
        contents:
          - text: "IAQM 2023"
            href: IAQM_2023.qmd
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

